/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controlador.controlMedico;
import DAO.CidadeDAO;
import DAO.EspecializacaoDAO;
import DAO.EstadoDAO;
import DAO.MedicoDAO;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cidade;
import modelo.Especializacao;
import modelo.Estado;
import modelo.Medico;

/**
 *
 * @author Nicolas
 */
public class ViewMedico extends javax.swing.JFrame {

    
    java.util.Date date;
    java.sql.Date sqldate = new java.sql.Date(date.getTime());
    
    
    String sexo;
    /**
     * Creates new form ViewMedico
     */
    public ViewMedico() {
        initComponents();
        
        EspecializacaoDAO edao = new EspecializacaoDAO();
        for(Especializacao e: edao.getAll()){
            especializacaoCombo.addItem(e);
        }
        
        CidadeDAO cidao = new CidadeDAO();
        for(Cidade c : cidao.getAll()){
            cidadeCombo.addItem(c);
        }
       
        
    }
    
        public void buscarTableId(int medicoId){
        DefaultTableModel modelo = (DefaultTableModel) jTableMedicosRegistrados.getModel();
        modelo.setNumRows(0);
        MedicoDAO mdao = new MedicoDAO();
        Medico m = new Medico();
        try{
        m = mdao.getById(medicoId);
        modelo.addRow(new Object[]{
            m.getMedicoId(),
            m.getNomeCompleto(),
            m.getNascimento(),
            m.getSexo(),
            m.getIdentidade(),
            m.getCPF(),
            m.getEspecializacao().getDesc(),
            m.getCidade().getNome(),
            
        });

        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Falha ao preencher a tabela: " + ex);
            limparTable();
        }
    }
    
         public void buscarTable(){
         
         DefaultTableModel modelo = (DefaultTableModel) jTableMedicosRegistrados.getModel();
         modelo.setNumRows(0);
         MedicoDAO mdao = new MedicoDAO();
         List<Medico> medicos = new ArrayList<>();
         medicos = mdao.getAll();

         try {
             for(Medico m : medicos){
                 modelo.addRow(new Object[]{
                 m.getMedicoId(),
                 m.getNomeCompleto(),
                 m.getNascimento(),
                 m.getSexo(),
                 m.getIdentidade(),
                 m.getCPF(),
                 m.getEspecializacao().getDesc(),
                 m.getCidade().getNome(),
                 }
                 );
                           
             }
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(null,"Falha ao preencher a Table" + ex);
             limparTable();
         }
     }
         
         public void limparTable(){
         txtNome.setText(null);
         txtNascimento.setText(null);
         jCheckBox1.setSelected(false);
         jCheckBox2.setSelected(false);
         txtIdentidade.setText(null);
         txtCPF.setText(null);
         especializacaoCombo.setSelectedItem(null);
         cidadeCombo.setSelectedItem(null);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton6 = new javax.swing.JButton();
        jInternalFrameCadastro = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        voltarBtn = new javax.swing.JButton();
        consultarBtn = new javax.swing.JButton();
        alterarBtn = new javax.swing.JButton();
        removerBtn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cadastrarBtn = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtNascimento = new javax.swing.JTextField();
        txtIdentidade = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        especializacaoCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMedicosRegistrados = new javax.swing.JTable();
        pesquisarPorIdBtn = new javax.swing.JButton();
        txtIdMedico = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cidadeCombo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemMedico = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuCidade = new javax.swing.JMenuItem();
        jMenuEstado = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemHome = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemFecharPrograma = new javax.swing.JMenuItem();

        jButton6.setText("jButton1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jInternalFrameCadastro.setClosable(true);
        jInternalFrameCadastro.setIconifiable(true);
        jInternalFrameCadastro.setMaximizable(true);
        jInternalFrameCadastro.setTitle("Cadastro de Medicos");
        jInternalFrameCadastro.setVisible(true);

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrameCadastroLayout = new javax.swing.GroupLayout(jInternalFrameCadastro.getContentPane());
        jInternalFrameCadastro.getContentPane().setLayout(jInternalFrameCadastroLayout);
        jInternalFrameCadastroLayout.setHorizontalGroup(
            jInternalFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrameCadastroLayout.setVerticalGroup(
            jInternalFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroLayout.createSequentialGroup()
                .addContainerGap(464, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema Gerenciamento da Clinica");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sistema de Gerenciamento de Médicos");

        voltarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(257, 257, 257)
                .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 926, 63);

        consultarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/procurar.png"))); // NOI18N
        consultarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(consultarBtn);
        consultarBtn.setBounds(10, 80, 52, 41);

        alterarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Update_984748.png"))); // NOI18N
        alterarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(alterarBtn);
        alterarBtn.setBounds(10, 135, 52, 41);

        removerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_f-cross_256_282471.png"))); // NOI18N
        removerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(removerBtn);
        removerBtn.setBounds(10, 187, 52, 41);

        jButton7.setText("Cancelar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(190, 430, 76, 37);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Sexo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 188, 29, 15);

        cadastrarBtn.setText("Salvar");
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarBtn);
        cadastrarBtn.setBounds(80, 430, 76, 37);

        jCheckBox1.setText("Masculino");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(80, 210, 80, 23);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Identidade");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 235, 59, 15);

        jCheckBox2.setText("Feminino");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(170, 210, 80, 23);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Cadastro de Pessoa Física (CPF)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 300, 184, 15);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Especialização");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 360, 85, 15);

        txtCPF.setToolTipText("XXX.XXX.XXX-XX");
        getContentPane().add(txtCPF);
        txtCPF.setBounds(80, 320, 183, 30);

        txtNascimento.setToolTipText("DD/MM/AAAA");
        getContentPane().add(txtNascimento);
        txtNascimento.setBounds(80, 156, 114, 30);

        txtIdentidade.setToolTipText("XX.XXX.XXX-X");
        getContentPane().add(txtIdentidade);
        txtIdentidade.setBounds(80, 256, 183, 30);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(80, 101, 321, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Nome Completo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 80, 90, 15);

        especializacaoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especializacaoComboActionPerformed(evt);
            }
        });
        getContentPane().add(especializacaoCombo);
        especializacaoCombo.setBounds(80, 380, 122, 30);

        jTableMedicosRegistrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome Completo", "Data de Nascimento", "Sexo", "RG", "CPF", "Especialização", "Cidade"
            }
        ));
        jTableMedicosRegistrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMedicosRegistradosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMedicosRegistrados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(418, 188, 452, 197);

        pesquisarPorIdBtn.setText("Pesquisar");
        pesquisarPorIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarPorIdBtnActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisarPorIdBtn);
        pesquisarPorIdBtn.setBounds(695, 396, 79, 30);

        txtIdMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdMedico);
        txtIdMedico.setBounds(516, 397, 136, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Pesquisar por ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(418, 399, 94, 15);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Data de Nascimento");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(80, 132, 114, 15);

        cidadeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeComboActionPerformed(evt);
            }
        });
        getContentPane().add(cidadeCombo);
        cidadeCombo.setBounds(280, 160, 110, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Cidade");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(280, 130, 80, 20);

        jMenuCadastro.setText("Cadastros");

        jMenuItemMedico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemMedico.setText("Médico");
        jMenuItemMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMedicoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemMedico);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Usuário");
        jMenuCadastro.add(jMenuItem4);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Especialização");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItem1);

        jMenuCidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuCidade.setText("Cidade");
        jMenuCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCidadeActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCidade);

        jMenuEstado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuEstado.setText("Estado");
        jMenuEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEstadoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuEstado);

        jMenuBar1.add(jMenuCadastro);

        jMenuRelatorios.setText("Relatórios");
        jMenuBar1.add(jMenuRelatorios);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemHome.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemHome.setText("Home");
        jMenuItemHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHomeActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemHome);

        jMenuBar1.add(jMenuFerramentas);

        jMenu1.setText("Sair");

        jMenuItemFecharPrograma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemFecharPrograma.setText("Fechar Programa");
        jMenuItemFecharPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFecharProgramaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemFecharPrograma);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(942, 544));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void especializacaoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especializacaoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especializacaoComboActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        new ViewPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarBtnActionPerformed

    private void txtIdMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMedicoActionPerformed

    private void consultarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBtnActionPerformed
        buscarTable();
    }//GEN-LAST:event_consultarBtnActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        Medico m = new Medico();
        Especializacao e = new Especializacao();
        Cidade c = new Cidade();
        MedicoDAO mdao = new MedicoDAO();
        controlMedico CM = new controlMedico();
        
        
        m.setNomeCompleto(txtNome.getText());
        m.setNascimento(sqldate);
        if(jCheckBox1.isSelected()){
            m.setSexo("Masculino");
        }
        else if(jCheckBox2.isSelected()){
            m.setSexo("Feminino");
        }
        sexo = m.getSexo();
        m.setIdentidade(txtIdentidade.getText());
        m.setCPF(txtCPF.getText());
        e = (Especializacao) especializacaoCombo.getSelectedItem();
        c = (Cidade) cidadeCombo.getSelectedItem();
        
        m.setEspecializacao(e);
        m.setCidade(c);
        
        CM.addMedico(e, c, txtNome.getText(), txtNascimento.getText(), sexo, txtIdentidade.getText(), txtCPF.getText());
        
        buscarTable();
        
    }//GEN-LAST:event_cadastrarBtnActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        
        jCheckBox2.setSelected(false);
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        
        jCheckBox1.setSelected(false);
        
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.txtNome.setText("");
        this.txtNascimento.setText("");
        this.txtIdentidade.setText("");
        this.txtCPF.setText("");
        this.jCheckBox1.setSelected(false);
        this.jCheckBox2.setSelected(false);
        this.especializacaoCombo.setSelectedIndex(-1);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void pesquisarPorIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarPorIdBtnActionPerformed
        Medico m = new Medico();
        
        MedicoDAO mdao = new MedicoDAO();
        
        
        m = mdao.getById(Integer.parseInt(txtIdMedico.getText()));
        
        txtNome.setText(m.getNomeCompleto());
        txtNascimento.setText(m.getNascimento());
        txtIdentidade.setText(m.getIdentidade());
        txtCPF.setText(m.getCPF());
        
        
        buscarTableId((int)m.getMedicoId());
    }//GEN-LAST:event_pesquisarPorIdBtnActionPerformed

    private void alterarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarBtnActionPerformed
        Medico m = new Medico();
        MedicoDAO edao = new MedicoDAO();
        Especializacao e = new Especializacao();
        Cidade c = new Cidade();
        
        String sexo;
        
        m.setMedicoId(Long.parseLong(txtIdMedico.getText()));
        m.setNomeCompleto(txtNome.getText());
        m.setNascimento(txtNascimento.getText());
        if(jCheckBox1.isSelected()){
            m.setSexo("Masculino");
        }
        else if(jCheckBox2.isSelected()){
            m.setSexo("Feminino");
        }
        sexo = m.getSexo();
        m.setIdentidade(txtIdentidade.getText());
        m.setCPF(txtCPF.getText());
        e = (Especializacao) especializacaoCombo.getSelectedItem();
        c = (Cidade) cidadeCombo.getSelectedItem();
        m.setCidade(c);
        
        m.setEspecializacao(e);
        
        
        edao.update(m);
        buscarTableId((int)m.getMedicoId());
    }//GEN-LAST:event_alterarBtnActionPerformed

    private void removerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBtnActionPerformed
        Medico m = new Medico();
        MedicoDAO mdao = new MedicoDAO();
        
        m = mdao.getById(Integer.parseInt(txtIdMedico.getText()));
        
        mdao.remove((int) m.getMedicoId());
    }//GEN-LAST:event_removerBtnActionPerformed

    private void jMenuItemMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMedicoActionPerformed
        new ViewMedico().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemMedicoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new ViewEspecializacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCidadeActionPerformed
        new ViewCidade().setVisible(true);
    }//GEN-LAST:event_jMenuCidadeActionPerformed

    private void jMenuEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEstadoActionPerformed
        new ViewEstado().setVisible(true);
    }//GEN-LAST:event_jMenuEstadoActionPerformed

    private void jMenuItemHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHomeActionPerformed
        new ViewPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemHomeActionPerformed

    private void jMenuItemFecharProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFecharProgramaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemFecharProgramaActionPerformed

    private void cidadeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeComboActionPerformed

    private void jTableMedicosRegistradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMedicosRegistradosMouseClicked
        MedicoDAO mdao = new MedicoDAO();
        
        mdao.orderByName();
        buscarTable();
    }//GEN-LAST:event_jTableMedicosRegistradosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JComboBox<Object> cidadeCombo;
    private javax.swing.JButton consultarBtn;
    private javax.swing.JComboBox<Object> especializacaoCombo;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JInternalFrame jInternalFrameCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuCidade;
    private javax.swing.JMenuItem jMenuEstado;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemFecharPrograma;
    private javax.swing.JMenuItem jMenuItemHome;
    private javax.swing.JMenuItem jMenuItemMedico;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMedicosRegistrados;
    private javax.swing.JButton pesquisarPorIdBtn;
    private javax.swing.JButton removerBtn;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtIdMedico;
    private javax.swing.JTextField txtIdentidade;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
